spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS public
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jooq:
    sql-dialect: h2
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

spring.main.web-application-type: none
